parameters:
    curlHelper.class:    Video\CommonBundle\Tools\CurlHelper
    curlHelper.class.authed:   FALSE
    fileUpload.class:     Video\CommonBundle\Tools\FileUpload
    fileUpload.class.base_upload_path:  "bundles/videoweb/"
services:
    curlHelper:
        class:    "%curlHelper.class%"
        arguments:    ["curlHelper.class.authed%"]
    baseREST:
        class: Video\CommonBundle\REST\BaseREST
        arguments: [@curlHelper,@service_container]
    canvasBaseREST:
        class: Video\CommonBundle\REST\Canvas\CanvasBaseREST
        parent: baseREST
    courseREST:
        class: Video\CommonBundle\REST\Canvas\CourseREST
        parent: canvasBaseREST
    enrollmentREST:
        class: Video\CommonBundle\REST\Canvas\EnrollmentREST
        parent: canvasBaseREST
    userREST:
        class: Video\CommonBundle\REST\Canvas\UserREST
        parent: canvasBaseREST
    fileREST:
        class: Video\CommonBundle\REST\Canvas\FileREST
        parent: canvasBaseREST
    moduleREST:
        class: Video\CommonBundle\REST\Canvas\ModuleREST
        parent: canvasBaseREST
    pageREST:
        class: Video\CommonBundle\REST\Canvas\PageREST
        parent: canvasBaseREST
    fileUpload:
        class:  "%fileUpload.class%"
        arguments:  ["%fileUpload.class.base_upload_path%"]

