parameters:
    curlHelper.class:    Video\CommonBundle\Tools\CurlHelper
    curlHelper.class.canvas_access_token:   IULKhnRJ2lVB5bza9NC70AUGnT9VtVaRgdt5737tlPhAGSMDVYcd7VBw9pfVR2GV
    curlHelper.class.base_url:   "https://canvas.example.com/api/v1/"
    curlHelper.class.authed:   FALSE
    fileUpload.class:     Video\CommonBundle\Tools\FileUpload
    fileUpload.class.base_upload_path:  "bundles/videoweb/"
services:
    curlHelper:
        class:    "%curlHelper.class%"
        arguments:    ["%curlHelper.class.canvas_access_token%","%curlHelper.class.base_url%","%curlHelper.class.authed%"]
    baseREST:
        class: Video\CommonBundle\REST\BaseREST
        arguments: [@curlHelper,@service_container]
    courseREST:
        class: Video\CommonBundle\REST\CourseREST
        parent: baseREST
    enrollmentREST:
        class: Video\CommonBundle\REST\EnrollmentREST
        parent: baseREST
    userREST:
        class: Video\CommonBundle\REST\UserREST
        parent: baseREST
    fileREST:
        class: Video\CommonBundle\REST\FileREST
        parent: baseREST
    moduleREST:
        class: Video\CommonBundle\REST\ModuleREST
        parent: baseREST
    pageREST:
        class: Video\CommonBundle\REST\PageREST
        parent: baseREST
    fileUpload:
        class:  "%fileUpload.class%"
        arguments:  ["%fileUpload.class.base_upload_path%"]

