video_web_homepage:
    path:     /hello/{name}
    defaults: { _controller: VideoWebBundle:Default:index }

index:
    path:     /
    defaults: { _controller: VideoWebBundle:Play:index }

show:
    path:     /show/{video_id}
    defaults: { _controller: VideoWebBundle:Play:show }
    methods: POST
    requirements:
              video_id: \d+
upload:
    path:     /upload
    defaults: { _controller: VideoWebBundle:File:upload }

download:
    path:     /download
    defaults: { _controller: VideoWebBundle:File:download }

delete:
    path:     /delete
    defaults: { _controller: VideoWebBundle:File:delete }
