video_web_homepage:
    path:     /hello/{name}
    defaults: { _controller: VideoWebBundle:Default:index }

index:
    path:     /
    defaults: { _controller: VideoWebBundle:Play:index }

show:
    path:     /show/{video_id}
    defaults: { _controller: VideoWebBundle:Play:show }
    methods: [POST]
    requirements:
              video_id: \d+
upload:
    path:     /upload
    defaults: { _controller: VideoWebBundle:File:upload }

download:
    path:     /download
    defaults: { _controller: VideoWebBundle:File:download }

delete:
    path:     /delete
    defaults: { _controller: VideoWebBundle:File:delete }
course_show:
    path:     /course
    defaults: { _controller: VideoWebBundle:Course:show }

chapter_show:
    path:     /course/{course_id}/chapter
    defaults: { _controller: VideoWebBundle:Chapter:show }
    requirements:
              course_id: \d+
choice:
    path:    /choice
    defaults: {_controller: VideoWebBundle:Canvas:choice }

find_chapters:
     path:   /findchapters
     defaults: {_controller: VideoWebBundle:Canvas:findChapters }

add_ex_url:
    path:     /addExUrl
    defaults: { _controller: VideoWebBundle:Canvas:addExUrl }
    methods: [POST]

to_create_token:
    path:     /tocreateToken
    defaults: { _controller: VideoWebBundle:Play:createToken }
    methods: [POST]